name: backendtemplate-dev-services
services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'backendtemplate'
    ports:
      - '65432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d backendtemplate -U test"]
      interval: 5s
      timeout: 5s
      retries: 5